global:
  hosts:
    domain: local
    https: false
  ingress:
    configureCertmanager: false
    class: traefik
nginx-ingress:
  enabled: false
prometheus:
  install: false
gitlab-runner:
  install: true

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1