apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: will-ingress
  namespace: dev
spec:
  ingressClassName: traefik
  replicas: 1
  rules:
  - host: "app1.com"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: wil-playground
            port:
              number: 8888
