server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
      traefik.ingress.kubernetes.io/router.tls: "false"
    hosts:
      - argocd.iot.local
