global:
  edition: ce
  hosts:
    domain: iot.local
    https: false
  ingress:
    configureCertmanager: false
    class: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
      traefik.ingress.kubernetes.io/router.tls: "false"

nginx-ingress:
  enabled: false
prometheus:
  install: false
gitlab-runner:
  install: false
registry:
  enabled: false
minio:
  ingress:
    enabled: false
