VM_CONTROL_NAME = "aaudeberS"

Vagrant.configure(2) do |config|
  config.vm.box = "generic/debian12"
  config.vm.synced_folder ".", "/share"

  config.vm.define VM_CONTROL_NAME do |control|
    control.vm.hostname = VM_CONTROL_NAME

    control.vm.network :private_network, ip: "192.168.56.110"

    control.vm.provider :virtualbox do |v|
      v.name = VM_CONTROL_NAME
      v.gui = false
      v.memory = 2048
      v.cpus = 2
    end

    control.vm.provision "shell", path: "./scripts/install_master.sh"
  end
end
