Vagrant.configure(2) do |config|
  config.vm.box = "generic/debian12"
  config.vm.synced_folder "k3s_setup", "/k3s_setup"

  config.trigger.after :destroy do |trigger|
    trigger.info = "Cleaning up VirtualBox VM folder for aaudeberS"
    trigger.run = { inline: "rm -rf /home/yorito/VirtualBox_VMs/aaudeberS" }
  end

  config.vm.define "aaudeberS" do |control|
    control.vm.hostname = "aaudeberS"

    control.vm.network :private_network, ip: "192.168.56.110"

    control.vm.provider :virtualbox do |v|
      v.name = "aaudeberS"
      v.gui = false
      v.memory = 1024
      v.cpus = 1
    end

    config.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-name aaudeberS --node-ip 192.168.56.110" sh -
      cd /k3s_setup
      kubectl apply -f ingress.yaml
      kubectl apply -f mongo-config.yaml
      kubectl apply -f mongo-secret.yaml
      kubectl apply -f mongo.yaml
      sleep 3
      kubectl apply -f app1.yaml
      kubectl apply -f app2.yaml
      kubectl apply -f app3.yaml
    SHELL
  end
end

