Vagrant.configure(2) do |config|
  config.vm.box = "generic/debian12"
  config.vm.synced_folder "./confs", "/vagrant", type: "virtualbox"

  config.vm.define "aaudeberS" do |control|
    control.vm.hostname = "aaudeberS"

    control.vm.network :private_network, ip: "192.168.56.110"

    control.vm.provider :virtualbox do |v|
      v.name = "aaudeberS"
      v.gui = false
      v.memory = 1024
      v.cpus = 2
    end
    server.vm.provision "shell", run: "once", path: "./scripts/Server.sh"
  end

  config.vm.define "aaudeberSW" do |control|
    control.vm.hostname = "aaudeberSW"

    control.vm.network :private_network, ip: "192.168.56.111"

    control.vm.provider :virtualbox do |v|
      v.name = "aaudeberSW"
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end

    control.vm.provision "shell", path: "./scripts/install_worker.sh"
  end
end
