Vagrant.configure(2) do |config|
  config.vm.box = "generic/debian12"
  config.vm.synced_folder ".", "/vagrant"

  config.trigger.after :destroy do
    system("rm -rf /home/yorito/VirtualBox_VMs/wilS")
    system("rm -rf /home/yorito/VirtualBox_VMs/wilSW")
  end

  config.vm.define "wilS" do |control|
    control.vm.hostname = "wilS"

    control.vm.network :private_network, ip: "192.168.56.110"

    control.vm.provider :virtualbox do |v|
      v.name = "wilS"
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end

    control.vm.provision "shell", path: "./install_master.sh"

  end

  config.vm.define "wilSW" do |control|
    control.vm.hostname = "wilSW"

    control.vm.network :private_network, ip: "192.168.56.111"

    control.vm.provider :virtualbox do |v|
      v.name = "wilSW"
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end

    control.vm.provision "shell", path: "./install_worker.sh"
  end
end
