Vagrant.configure(2) do |config|
  config.vm.box = "generic/debian12"
  config.vm.synced_folder ".", "/vagrant"

  config.trigger.after :destroy do |trigger|
    trigger.info = "Cleaning up VirtualBox VM folder for aaudeberS"
    trigger.run = { inline: "rm -rf /home/yorito/VirtualBox_VMs/aaudeberS" }
    trigger.run = { inline: "rm -rf /home/yorito/VirtualBox_VMs/aaudeberSW" }
  end

  config.vm.define "aaudeberS" do |control|
    control.vm.hostname = "aaudeberS"

    control.vm.network :private_network, ip: "192.168.56.110"

    control.vm.provider :virtualbox do |v|
      v.name = "aaudeberS"
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end

    control.vm.provision "shell", path: "./install_master.sh"

  end

  config.vm.define "aaudeberSW" do |control|
    control.vm.hostname = "aaudeberSW"

    control.vm.network :private_network, ip: "192.168.56.111"

    control.vm.provider :virtualbox do |v|
      v.name = "aaudeberSW"
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end

    control.vm.provision "shell", path: "./install_worker.sh"
  end
end
