Vagrant.configure(2) do |config|
  config.vm.box = "generic/debian12"
  config.vm.synced_folder ".", "/share"

  config.vm.define "aaudeberS" do |control|
    control.vm.hostname = "aaudeberS"

    control.vm.network :private_network, ip: "192.168.56.110"
    control.vm.network "forwarded_port", guest: 8080, host: 8080

    control.vm.provider :virtualbox do |vb|
      vb.name = "aaudeberS"
      vb.memory = 4096
      vb.cpus = 2
      vb.gui = false
    end

    control.vm.provision "shell", path: "./scripts/provisioning.sh"
  end
end
