VM_CONTROL_NAME = "lle-saulS"

Vagrant.configure(2) do |config|
  config.vm.box = "generic/debian12"
  config.vm.synced_folder ".", "/share"

  config.vm.define VM_CONTROL_NAME do |control|
    control.vm.hostname = VM_CONTROL_NAME

    control.vm.network :private_network, ip: "192.168.56.111"
    control.vm.network "forwarded_port", guest: 8000, host: 8001

    control.vm.provider :virtualbox do |vb|
      vb.name = VM_CONTROL_NAME
      vb.memory = 4096
      vb.cpus = 6
      vb.gui = false
    end

    control.vm.provision "shell", path: "./scripts/install.sh"
  end
end
